name: Kudus Bilinci Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Repository'yi al
        uses: actions/checkout@v6

      - name: GitHub Pages'i hazırla
        uses: actions/configure-pages@v5

      - name: Uygulama dosyalarını yükle
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./kudus_bilinci_final_static

      - name: Yayınla
        id: deployment
        uses: actions/deploy-pages@v4
